import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Eye, FolderOpen, Pencil, Plus, Search } from 'lucide-react';
import { api, post, type CaseOptions, type LegalCase, type Page } from './api';
import { SearchableSelect } from './SearchableSelect';
import { ResponsiveDataRow } from './ResponsiveDataTable';

const statuses: Record<string, string> = { OPEN: 'Abierto', IN_PROGRESS: 'En progreso', SUSPENDED: 'Suspendido', CLOSED: 'Cerrado' };
const priorities: Record<string, string> = { LOW: 'Baja', MEDIUM: 'Media', HIGH: 'Alta', URGENT: 'Urgente' };
const errorText = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.';
const Alert = ({ children }: { children: ReactNode }) => children ? <div className="alert" role="alert">{children}</div> : null;
const Loading = () => <div className="loading" role="status"><span className="spinner"/>Cargando casos…</div>;
const Input = ({ label, name, type = 'text', value }: { label: string; name: string; type?: string; value?: string }) =>
  <label className="field">{label}<input required name={name} type={type} maxLength={256} defaultValue={value}/></label>;

export function Cases() {
  const [params, setParams] = useSearchParams(); const [page, setPage] = useState<Page<LegalCase> | null>(null);
  const [options, setOptions] = useState<CaseOptions>({ clients: [], responsibleMemberships: [], caseStatuses: [], caseTypes: [], courts: [], jurisdictions: [] });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const query = params.toString();
  useEffect(() => { api<CaseOptions>('/cases/options').then(setOptions).catch(e => setError(errorText(e))); }, []);
  useEffect(() => { let live = true; setLoading(true); api<Page<LegalCase>>(`/cases${query ? `?${query}` : ''}`).then(x => { if (live) setPage(x); })
    .catch(e => { if (live) setError(errorText(e)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [query]);
  function filter(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const next = new URLSearchParams();
    for (const key of ['search','status','priority','clientId','responsibleMembershipId']) { const value = String(data.get(key) ?? '').trim(); if (value) next.set(key, value); } setParams(next); }
  return <><div className="page-heading"><div><span className="eyebrow">EXPEDIENTES LEGALES</span><h1>Casos</h1><p className="muted">Casos y expedientes de tu organización.</p></div><Link className="button" to="/app/cases/new"><Plus size={17}/>Nuevo caso</Link></div><Alert>{error}</Alert>
    <form className="panel case-filters" onSubmit={filter}><label><Search size={17}/><input name="search" aria-label="Buscar casos" placeholder="Número, título, cliente, contraparte o juzgado" defaultValue={params.get('search') ?? ''}/></label>
      <select name="status" aria-label="Estado" defaultValue={params.get('status') ?? ''}><option value="">Todos los estados</option>{Object.entries(statuses).map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select>
      <select name="priority" aria-label="Prioridad" defaultValue={params.get('priority') ?? ''}><option value="">Todas las prioridades</option>{Object.entries(priorities).map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select>
      <select name="clientId" aria-label="Cliente" defaultValue={params.get('clientId') ?? ''}><option value="">Todos los clientes</option>{options.clients.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select name="responsibleMembershipId" aria-label="Responsable" defaultValue={params.get('responsibleMembershipId') ?? ''}><option value="">Todos los responsables</option>{options.responsibleMemberships.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button secondary">Filtrar</button></form>
    <section className="panel clients-table responsive-data-table"><div className="table-heading"><h2>Expedientes</h2><span className="count">{page?.totalCount ?? 0}</span></div>{loading ? <Loading/> : !page?.items.length ? <div className="empty-state"><FolderOpen size={32}/><h3>No hay casos para mostrar</h3><p>Crea un caso o modifica los filtros.</p></div> : <div className="table-scroll"><table><thead><tr><th aria-label="Detalles"/><th>Número</th><th>Caso / título</th><th>Cliente</th><th>Tipo</th><th>Responsable</th><th>Estado</th><th>Prioridad</th><th>Apertura</th><th>Acción</th></tr></thead><tbody>{page.items.map(item => <ResponsiveDataRow key={item.id} id={item.id} cells={[<strong>{item.caseNumber}</strong>,item.title,item.clientName,item.caseType,item.responsibleName || '—',<span className={`case-status ${item.status.toLowerCase()}`}>{statuses[item.status] ?? item.status}</span>,<span className={`case-priority ${item.priority.toLowerCase()}`}>{priorities[item.priority]}</span>,new Date(item.openedAt).toLocaleDateString('es'),<Link className="icon-button" title="Ver caso" to={`/app/cases/${item.id}`}><Eye size={17}/></Link>]} details={[{label:'Tipo',value:item.caseType},{label:'Responsable',value:item.responsibleName},{label:'Prioridad',value:priorities[item.priority]},{label:'Fecha de situación',value:item.situationDate ? new Date(item.situationDate).toLocaleDateString('es') : '—'},{label:'Fecha de apertura',value:new Date(item.openedAt).toLocaleDateString('es')},{label:'Tribunal',value:item.court},{label:'Jurisdicción',value:item.jurisdiction}]}/>)}</tbody></table></div>}
      {!!page?.totalPages && page.totalPages > 1 && <div className="pagination"><button disabled={page.page === 1} onClick={() => { const next = new URLSearchParams(params); next.set('page', String(page.page - 1)); setParams(next); }}>Anterior</button><span>Página {page.page} de {page.totalPages}</span><button disabled={page.page === page.totalPages} onClick={() => { const next = new URLSearchParams(params); next.set('page', String(page.page + 1)); setParams(next); }}>Siguiente</button></div>}</section></>;
}

export function CaseForm() {
  const { id } = useParams(); const editing = !!id; const navigate = useNavigate(); const [item, setItem] = useState<LegalCase | null>(null);
  const [options, setOptions] = useState<CaseOptions>({ clients: [], responsibleMemberships: [], caseStatuses: [], caseTypes: [], courts: [], jurisdictions: [] }); const [error, setError] = useState(''); const [optionsError,setOptionsError]=useState(''); const [optionsLoading,setOptionsLoading]=useState(true); const [busy, setBusy] = useState(false);
  useEffect(() => { setOptionsLoading(true); api<CaseOptions>('/cases/options').then(setOptions).catch(e => setOptionsError(errorText(e))).finally(()=>setOptionsLoading(false)); if (id) api<LegalCase>(`/cases/${id}`).then(setItem).catch(e => setError(errorText(e))); }, [id]);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const data = new FormData(e.currentTarget);
    const body: Record<string, FormDataEntryValue | null> = Object.fromEntries(data.entries()); for (const key of ['responsibleMembershipId','courtId','jurisdictionId']) if (!body[key]) body[key] = null;
    try { const saved = editing ? await api<LegalCase>(`/cases/${id}`, { method: 'PUT', body: JSON.stringify(body) }) : await post<LegalCase>('/cases', body); navigate(`/app/cases/${saved.id}`); }
    catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  if (editing && !item && !error) return <Loading/>;
  return <><div className="page-heading"><div><Link className="back-link" to={editing ? `/app/cases/${id}` : '/app/cases'}><ArrowLeft size={15}/>Volver</Link><h1>{editing ? 'Editar caso' : 'Nuevo caso'}</h1><p className="muted">Información principal del expediente.</p></div></div><Alert>{error}</Alert>
    <form className="panel client-form" onSubmit={save}><div className="form-section"><h2>Identificación</h2><div className="form-row"><Input label="Número de caso / expediente" name="caseNumber" value={item?.caseNumber}/><Input label="Título" name="title" value={item?.title}/></div><div className="form-row"><SearchableSelect required label="Cliente" name="clientId" value={item?.clientId} options={options.clients} loading={optionsLoading} error={optionsError}/><SearchableSelect required label="Tipo de caso" name="caseTypeId" value={item?.caseTypeId} options={options.caseTypes} loading={optionsLoading} error={optionsError}/></div><label className="field">Descripción<textarea name="description" maxLength={4000} defaultValue={item?.description}/></label></div>
      <div className="form-section"><h2>Gestión</h2><div className="form-row"><SearchableSelect required label="Estado" name="caseStatusId" value={item?.caseStatusId} options={options.caseStatuses} loading={optionsLoading} error={optionsError}/><label className="field">Prioridad<select name="priority" defaultValue={item?.priority ?? 'MEDIUM'}>{Object.entries(priorities).map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select></label></div><div className="form-row"><SearchableSelect label="Responsable" name="responsibleMembershipId" value={item?.responsibleMembershipId} options={options.responsibleMemberships} loading={optionsLoading} error={optionsError}/><Input label="Fecha de situación" name="situationDate" type="date" value={item?.situationDate?.slice(0,10)}/><Input label="Fecha de apertura" name="openedAt" type="date" value={item?.openedAt.slice(0,10) ?? new Date().toISOString().slice(0,10)}/></div></div>
      <div className="form-section"><h2>Información judicial</h2><div className="form-row"><SearchableSelect label="Tribunal / juzgado" name="courtId" value={item?.courtId} options={options.courts} loading={optionsLoading} error={optionsError}/><SearchableSelect label="Jurisdicción" name="jurisdictionId" value={item?.jurisdictionId} options={options.jurisdictions} loading={optionsLoading} error={optionsError}/></div><div className="form-row"><Input label="Contraparte" name="counterparty" value={item?.counterparty}/><Input label="Abogado contrario" name="opposingCounsel" value={item?.opposingCounsel}/></div><label className="field">Notas<textarea name="notes" maxLength={4000} defaultValue={item?.notes}/></label></div>
      <div className="form-actions"><Link className="button secondary" to={editing ? `/app/cases/${id}` : '/app/cases'}>Cancelar</Link><button className="button" disabled={busy}>{busy ? 'Guardando…' : 'Guardar caso'}</button></div></form></>;
}

export function CaseDetail() {
  const { id } = useParams(); const [item, setItem] = useState<LegalCase | null>(null); const [tab, setTab] = useState('Resumen'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api<LegalCase>(`/cases/${id}`).then(setItem).catch(e => setError(errorText(e))); }, [id]);
  async function toggle() { if (!item) return; setBusy(true); try { setItem(await api<LegalCase>(`/cases/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: item.status === 'CLOSED' ? 'OPEN' : 'CLOSED' }) })); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  if (!item && !error) return <Loading/>;
  return <><Alert>{error}</Alert>{item && <><div className="page-heading case-heading"><div><Link className="back-link" to="/app/cases"><ArrowLeft size={15}/>Casos</Link><span className="eyebrow">{item.caseNumber}</span><h1>{item.title}</h1><p className="muted">{item.clientName} · Abierto el {new Date(item.openedAt).toLocaleDateString('es')}</p></div><div className="heading-actions"><button className="button secondary" onClick={toggle} disabled={busy}>{item.status === 'CLOSED' ? 'Reabrir' : 'Cerrar caso'}</button><Link className="button" to={`/app/cases/${id}/edit`}><Pencil size={16}/>Editar</Link></div></div>
    <div className="case-meta"><span className={`case-status ${item.status.toLowerCase()}`}>{statuses[item.status]}</span><span className={`case-priority ${item.priority.toLowerCase()}`}>{priorities[item.priority]}</span><span>Responsable: {item.responsibleName || 'Sin asignar'}</span>{item.closedAt && <span>Cerrado: {new Date(item.closedAt).toLocaleDateString('es')}</span>}</div>
    <div className="case-tabs" role="tablist">{['Resumen','Seguimientos','Tareas','Agenda','Documentos'].map(name => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div>
    {tab === 'Resumen' ? <div className="client-detail-grid"><section className="panel detail-card full-detail"><h2>Resumen del caso</h2><p>{item.description || 'Sin descripción.'}</p></section><section className="panel detail-card"><h2>Información judicial</h2><dl><dt>Tribunal</dt><dd>{item.court || '—'}</dd><dt>Jurisdicción</dt><dd>{item.jurisdiction || '—'}</dd><dt>Tipo</dt><dd>{item.caseType}</dd></dl></section><section className="panel detail-card"><h2>Partes</h2><dl><dt>Contraparte</dt><dd>{item.counterparty || '—'}</dd><dt>Abogado contrario</dt><dd>{item.opposingCounsel || '—'}</dd></dl></section><section className="panel detail-card full-detail"><h2>Notas</h2><p>{item.notes || 'Sin notas.'}</p></section></div> : <section className="panel empty-state future-tab"><FolderOpen size={32}/><h3>{tab}</h3><p>Este espacio quedará disponible en un próximo sprint.</p></section>}</>}</>;
}
