import { useEffect, useState, type FormEvent } from 'react';
import { Pencil, X } from 'lucide-react';
import { api, post, type CatalogItem } from './api';

const labels = { 'case-statuses': 'Estados de caso', 'case-types': 'Tipos de caso', courts: 'Tribunales / Juzgados', jurisdictions: 'Jurisdicciones' } as const;
type Key = keyof typeof labels;

export function SettingsCatalogs() {
  const [kind,setKind]=useState<Key>('case-statuses'); const [items,setItems]=useState<CatalogItem[]>([]); const [editing,setEditing]=useState<CatalogItem|null>(null);
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{setItems(await api<CatalogItem[]>(`/settings/${kind}`));}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.')}finally{setLoading(false)}}
  useEffect(()=>{setEditing(null);setError('');setSuccess('');load();},[kind]);
  function beginEdit(item:CatalogItem){setEditing(item);setError('');setSuccess('');window.scrollTo({top:0,behavior:'smooth'});}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setSuccess('');const d=new FormData(e.currentTarget);const body=kind==='case-statuses'?{name:d.get('name'),code:d.get('code'),sortOrder:Number(d.get('sortOrder')),isOpen:d.has('isOpen'),isClosed:d.has('isClosed'),isInnocent:d.has('isInnocent'),isGuilty:d.has('isGuilty')}:{name:d.get('name'),sortOrder:Number(d.get('sortOrder'))};try{if(editing)await api(`/settings/${kind}/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await post(`/settings/${kind}`,body);setSuccess(editing?'Registro actualizado correctamente.':'Registro creado correctamente.');setEditing(null);e.currentTarget.reset();await load();}catch(x){setError(x instanceof Error?x.message:'No se pudo guardar.');}finally{setBusy(false)}}
  async function toggle(x:CatalogItem){setBusy(true);setError('');setSuccess('');try{await api(`/settings/${kind}/${x.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!x.isActive})});setSuccess(x.isActive?'Registro desactivado.':'Registro activado.');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setBusy(false)}}
  return <><div className="page-heading"><div><span className="eyebrow">CONFIGURACIÓN</span><h1>Tablas administrables</h1><p className="muted">Catálogos propios de tu organización.</p></div></div>{error&&<div className="alert catalog-feedback" role="alert">{error}</div>}{success&&<div className="alert success catalog-feedback" role="status">{success}</div>}
    <div className="settings-tabs">{Object.entries(labels).map(([k,v])=><button key={k} className={kind===k?'active':''} onClick={()=>setKind(k as Key)}>{v}</button>)}</div>
    <form key={`${kind}-${editing?.id??'new'}`} className="panel catalog-form" onSubmit={save}><label className="field">Nombre<input required name="name" defaultValue={editing?.name}/></label>{kind==='case-statuses'&&<><label className="field">Código<input required name="code" defaultValue={editing?.code}/></label><div className="catalog-flags">{(['isOpen','isClosed','isInnocent','isGuilty'] as const).map((x,i)=><label key={x}><input type="checkbox" name={x} defaultChecked={!!editing?.[x]}/>{['Abierto','Cerrado','Inocente','Culpable'][i]}</label>)}</div></>}<label className="field">Orden<input name="sortOrder" type="number" defaultValue={editing?.sortOrder??0}/></label><button className="button" disabled={busy}>{editing?'Guardar cambios':'Agregar'}</button>{editing&&<button type="button" className="button secondary" onClick={()=>setEditing(null)}><X size={16}/>Cancelar</button>}</form>
    <section className="panel catalog-list"><div className="table-heading"><h2>{labels[kind]}</h2><span className="count">{items.length}</span></div>{loading?<div className="loading"><span className="spinner"/>Cargando catálogo…</div>:items.map(x=><div className="catalog-row" key={x.id}><div><strong>{x.name}</strong>{x.code&&<small>{x.code}</small>}</div><span className={`client-status ${x.isActive?'active':'inactive'}`}>{x.isActive?'Activo':'Inactivo'}</span><div className="catalog-row-actions"><button className="button secondary" disabled={busy} onClick={()=>beginEdit(x)}><Pencil size={15}/>Editar</button><button className="button secondary" disabled={busy} onClick={()=>toggle(x)}>{x.isActive?'Desactivar':'Activar'}</button></div></div>)}</section></>;
}
